name: Docker

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ prod ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker
      run: make docker

